# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Random Walk Metropolis sampler using Rcpp
#' @description A Random Walk Metropolis sampler using Rcpp
#' @useDynLib SC19085
#' @import Rcpp
#' @param sigma the standard deviation of the normal random increment with a zero mean 
#' @param x0 the initial iteration point
#' @param N the designated number of random numbers (including the initial point x0)
#' @return a list of length 3, x the random numbers of size \code{N}, k the number of rejection times, acceptance_rate the acceptance rate of the candidate points 
#' @examples
#' \dontrun{
#' laplace<-function(x) return(1/2*exp(-abs(x)))
#' lapC <- rw_Metro_C(2,25,2000);
#' plot(1:2000,lapC$x,type='l')
#' abline(h=c(-3*sqrt(2),3*sqrt(2)))
#' }
#' @export
rw_Metro_C <- function(sigma, x0, N) {
    .Call('_SC19085_rw_Metro_C', PACKAGE = 'SC19085', sigma, x0, N)
}

